<a href="https://colab.research.google.com/github/ashartn123/python-workshop/blob/master/Copy_of_Day3_Session1_Exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1.Write a Pandas program to create and display a one-dimensional array using series containing event numbers upto 10000

tip : use List Comprehension ds = pd.Series([0,2, 4, 6, 8..... 10000])

In [ ]:
import pandas as pd
ds = pd.Series([x for x in range(1000) if x%2==0])
print(ds)

0        0
1        2
2        4
3        6
4        8
      ... 
495    990
496    992
497    994
498    996
499    998
Length: 500, dtype: int64


2.Write a Pandas program to convert a Panda module Series of the numbers which are between 1000 and 2000 (both inclusive) and divisable by 5 to Python list and after convertion print its type

In [ ]:
import pandas as pd
ds = pd.Series([x for x in range(1000,2000) if x%5==0])
print(ds)

0      1000
1      1005
2      1010
3      1015
4      1020
       ... 
195    1975
196    1980
197    1985
198    1990
199    1995
Length: 200, dtype: int64


#Exercises

1.Write a Pandas program to create and display a one-dimensional array using series containing event numbers upto 10000

In [ ]:
import pandas as pd
ds = pd.Series([x for x in range(1000) if x%2==0])
print(ds)

0        0
1        2
2        4
3        6
4        8
      ... 
495    990
496    992
497    994
498    996
499    998
Length: 500, dtype: int64


2.Write a Pandas program to convert a Panda module Series of the numbers which are between 1000 and 2000 (both inclusive) and divisable by 5 to Python list and after convertion print its type

In [ ]:
import pandas as pd
ds = pd.Series([x for x in range(1000,2000) if x%5==0])
print(ds)

0      1000
1      1005
2      1010
3      1015
4      1020
       ... 
195    1975
196    1980
197    1985
198    1990
199    1995
Length: 200, dtype: int64


3.Write a Pandas program to add, subtract, multiple and divide two Pandas Series and print their results using the Sample Series: [2, 4, 6, 8, ...100], [1, 3, 5, 7, 9...99]

In [ ]:
import pandas as pd
ds1 = pd.Series([2, 4, 6, 8, 10])
ds2 = pd.Series([1, 3, 5, 7, 9])
ds = ds1 + ds2
print("Add two Series:")
print(ds)
print("Subtract two Series:")
ds = ds1 - ds2
print(ds)
print("Multiply two Series:")
ds = ds1 * ds2
print(ds)
print("Divide Series1 by Series2:")
ds = ds1 / ds2
print(ds)

Add two Series:
0     3
1     7
2    11
3    15
4    19
dtype: int64
Subtract two Series:
0    1
1    1
2    1
3    1
4    1
dtype: int64
Multiply two Series:
0     2
1    12
2    30
3    56
4    90
dtype: int64
Divide Series1 by Series2:
0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.111111
dtype: float64


4.Write a Pandas program to compare (Equivalence, greater than, less than, not equal to )the elements of the two Pandas Series.
Sample Series: [All positive numbers divisable by 7 upto 1000], [All positive numbers divisable by 11 upto 1000]

In [ ]:
import pandas as pd
ds1 = pd.Series([2, 4, 6, 8, 10])
ds2 = pd.Series([1, 3, 5, 7, 10])
print("Series1:")
print(ds1)
print("Series2:")
print(ds2)
print("Compare the elements of the said Series:")
print("Equals:")
print(ds1 == ds2)
print("Greater than:")
print(ds1 > ds2)
print("Less than:")
print(ds1 < ds2)

Series1:
0     2
1     4
2     6
3     8
4    10
dtype: int64
Series2:
0     1
1     3
2     5
3     7
4    10
dtype: int64
Compare the elements of the said Series:
Equals:
0    False
1    False
2    False
3    False
4     True
dtype: bool
Greater than:
0     True
1     True
2     True
3     True
4    False
dtype: bool
Less than:
0    False
1    False
2    False
3    False
4    False
dtype: bool


5.Write a Pandas program to convert a NumPy array to a Pandas series.
Sample NumPy array: d1 = [10, 20, 30, 40, 50... 1000]

In [ ]:
import numpy as np
import pandas as pd
np_array = np.array([10, 20, 30, 40, 50])
print("NumPy array:")
print(np_array)
new_series = pd.Series(np_array)
print("Converted Pandas series:")
print(new_series)

NumPy array:
[10 20 30 40 50]
Converted Pandas series:
0    10
1    20
2    30
3    40
4    50
dtype: int64


6.Write a Pandas program to convert a given Series to an array.
Sample series is ['100', '200', ‘300’,’400’,’500’,'python', '300.12', '400',’is’,’great’,’language’]

In [ ]:
import pandas as pd
import numpy as np
s1 = pd.Series(['100', '200', '300','400','500','python', '300.12', '400','is','great','language'])
print("Original Data Series:")
print(s1)
print("Series to an array")
a = np.array(s1.values.tolist())
print (a)

Original Data Series:
0          100
1          200
2          300
3          400
4          500
5       python
6       300.12
7          400
8           is
9        great
10    language
dtype: object
Series to an array
['100' '200' '300' '400' '500' 'python' '300.12' '400' 'is' 'great'
 'language']


7.Write a Pandas program to sort a given Series.
Sample series is ['100', '200', ‘300’,’400’,’500’,'python', '300.12', '400',’is’,’great’,’language’]

In [ ]:
import pandas as pd
import numpy as np
s1 = pd.Series(['100', '200', '300','400','500','python', '300.12', '400','is','great','language'])
print("Original Data Series:")
print(s1)
print("Series to an array")
a = np.array(s1.values.tolist())
a.sort()
print (a)

Original Data Series:
0          100
1          200
2          300
3          400
4          500
5       python
6       300.12
7          400
8           is
9        great
10    language
dtype: object
Series to an array
['100' '200' '300' '300.12' '400' '400' '500' 'great' 'is' 'language'
 'python']


8.Write a Pandas program to create a subsets of a given series based on value and condition.

Sample NumPy array: d1 = [10, 20, 30, 40, 50... 1000] value and condtion : Subset 1 :numbers divisable by 7 Subset 2 : numbers divisable by 5'''


In [ ]:
import pandas as pd
s = pd.Series([0, 1,2,3,4,5,6,7,8,9,10])
print("Original Data Series:")
print(s)
print("\nSubset of the above Data Series:")
n = 6
new_s = s[s < n]
print(new_s)

Original Data Series:
0      0
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
dtype: int64

Subset of the above Data Series:
0    0
1    1
2    2
3    3
4    4
5    5
dtype: int64


9.Write a Pandas program to create the mean and standard deviation, maximum and minimum of the data of a given Series of the prime numbers upto 1000

In [ ]:
import pandas as pd
s = pd.Series(data = [x for x in range(1000) if x%2==0])
print("Original Data Series:")
print(s)
print("Mean of the said Data Series:")
print(s.mean())
print("Standard deviation of the said Data Series:")
print(s.std())

Original Data Series:
0        0
1        2
2        4
3        6
4        8
      ... 
495    990
496    992
497    994
498    996
499    998
Length: 500, dtype: int64
Mean of the said Data Series:
499.0
Standard deviation of the said Data Series:
288.9636655359978


10.Write a Pandas program to get the elements of an array values into column-wise.

Sample data: {‘X’:[All odd numbers but not divisable by 7 upto 1000], 'Y':[ All even numbers but not divisable by 5 upto 1000 ],'Z':[ All odd numbers but not divisable by 3 upto 1000]}

In [ ]:
import pandas as pd
df = pd.DataFrame({'X':[78,85,96,80,86], 'Y':[84,94,89,83,86],'Z':[86,97,96,72,83]});
print(df)

    X   Y   Z
0  78  84  86
1  85  94  97
2  96  89  96
3  80  83  72
4  86  86  83


11.Write a Pandas program to display the first 10 rows of the DataFrame for any particular three fields.

In [ ]:
import pandas as pd
import numpy as np

exam_data  = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
        'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
        'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(exam_data , index=labels)
print("First three rows of the data frame:")
print(df.iloc[:3])


!pip install -U -q PyDrive
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials


auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

downloaded = drive.CreateFile({'id':'19x9NcgKGDT71QP-Hsnl4lixX8J-edhan'}) # replace the id with id of file you want to access
downloaded.GetContentFile('movies_metadata.csv') 

import pandas as pd
xyz = pd.read_csv('movies_metadata.csv') 
print(xyz.head(1))

First three rows of the data frame:
        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
   adult  ... vote_count
0  False  ...     5415.0

[1 rows x 24 columns]


/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (10) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


12.Write a Pandas program to get the details of the seventh movie of the DataFrame for any particular three fields #(movie_metadata.csv file)

In [ ]:
import pandas as pd
df = pd.read_csv('movies_metadata.csv')
seventh_movie = df.iloc[3]
print("Details of the seventh movie:")
print(seventh_movie)

Details of the seventh movie:
adult                                                                False
belongs_to_collection                                                  NaN
budget                                                            16000000
genres                   [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...
homepage                                                               NaN
id                                                                   31357
imdb_id                                                          tt0114885
original_language                                                       en
original_title                                           Waiting to Exhale
overview                 Cheated on, mistreated and stepped on, the wom...
popularity                                                         3.85949
poster_path                               /16XOMpEaLWkrcPqSQqhTmeJuqQl.jpg
production_companies     [{'name': 'Twentieth Century Fox Film Corpora

/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (10) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


13.Write a Pandas program to sort the DataFrame based on title_year from dataset of movie_metadata.csv for any particular three fields

In [ ]:
import pandas as pd
df = pd.read_csv('movies_metadata.csv')
result = df[['title', 'genres']]
print("Details of title and genres:")
print(result)

Details of title and genres:
                             title                                             genres
0                        Toy Story  [{'id': 16, 'name': 'Animation'}, {'id': 35, '...
1                          Jumanji  [{'id': 12, 'name': 'Adventure'}, {'id': 14, '...
2                 Grumpier Old Men  [{'id': 10749, 'name': 'Romance'}, {'id': 35, ...
3                Waiting to Exhale  [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...
4      Father of the Bride Part II                     [{'id': 35, 'name': 'Comedy'}]
...                            ...                                                ...
45461                       Subdue  [{'id': 18, 'name': 'Drama'}, {'id': 10751, 'n...
45462          Century of Birthing                      [{'id': 18, 'name': 'Drama'}]
45463                     Betrayal  [{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...
45464             Satan Triumphant                                                 []
45465                    

/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (10) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


14.Write a Pandas program to sort the DataFrame based on country and language from dataset of movie_metadata.csv

In [ ]:
import pandas as pd
df = pd.read_csv('movies_metadata.csv')
# Create a smaller dataframe
small_df = df[['title', 'release_date', 'budget', 'revenue', 'runtime']]
result = small_df.sort_values('release_date')
print("DataFrame based on country and language.")

DataFrame based on country and language.


/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (10) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


15.Write a NumPy program to create a random 4x4 array and extract the 2nd and 3rd rows of the array and store them into a variable

In [ ]:
import numpy as np
x = np.random.random((4,4))
print("Original Array:")
print(x) 

Original Array:
[[0.30939937 0.79989946 0.69485734 0.32400584]
 [0.75101829 0.84378872 0.45749516 0.39088661]
 [0.21153759 0.49754225 0.96072598 0.14268348]
 [0.55381486 0.57858721 0.10375811 0.05328816]]


16.Write a NumPy program to create a 10x10 array with random values and find the minimum and maximum values.

In [ ]:
import numpy as np
x = np.random.random((10,10))
print("Original Array:")
print(x) 
xmin, xmax = x.min(), x.max()
print("Minimum and Maximum Values:")
print(xmin, xmax)

Original Array:
[[0.82627219 0.18157957 0.35301609 0.93171981 0.14273467 0.11045119
  0.89518037 0.75486895 0.17832694 0.86697641]
 [0.89158464 0.70548828 0.78377572 0.92799348 0.07404849 0.80507069
  0.62606738 0.61271819 0.8915418  0.58437635]
 [0.18931635 0.00213271 0.76512099 0.06763499 0.15352217 0.16289165
  0.08764386 0.50738044 0.07981339 0.51432068]
 [0.46730211 0.01704047 0.81814442 0.22303033 0.81288499 0.16404264
  0.24434614 0.07303804 0.9952399  0.5817909 ]
 [0.97824274 0.63436702 0.15198199 0.86522569 0.0448245  0.9077337
  0.22499053 0.50035404 0.02556835 0.59894326]
 [0.90396357 0.0333929  0.75273164 0.67713106 0.56400158 0.68333039
  0.81010109 0.39897779 0.83385405 0.24638834]
 [0.26373877 0.84606949 0.50044728 0.1035907  0.17887685 0.82541311
  0.04373673 0.28366725 0.34207499 0.04097218]
 [0.30456997 0.64748288 0.25933415 0.16302306 0.6090709  0.14351217
  0.4678639  0.01489494 0.05121567 0.38702515]
 [0.12688108 0.15296859 0.07853739 0.50237963 0.61674266 0.709280

17.Write a NumPy program to generate 8 random integers between 100 and 300

In [ ]:
import numpy as np
x = np.random.randint(low=100, high=300, size=8)
print(x)

[125 157 208 195 208 131 189 282]


18.Write a NumPy program to create a random integer nos of size 20 and sort it

In [ ]:
import numpy as np
x = np.random.random(20)
print("Original array:")
print(x)
x.sort()
print("Sorted array:")
print(x)

Original array:
[0.91824549 0.60256873 0.17520749 0.05902493 0.03309625 0.59383775
 0.21503852 0.40577183 0.44851452 0.32601552 0.8171542  0.82412037
 0.96796023 0.63668232 0.76324504 0.09225446 0.28207012 0.84518992
 0.24814908 0.45768093]
Sorted array:
[0.03309625 0.05902493 0.09225446 0.17520749 0.21503852 0.24814908
 0.28207012 0.32601552 0.40577183 0.44851452 0.45768093 0.59383775
 0.60256873 0.63668232 0.76324504 0.8171542  0.82412037 0.84518992
 0.91824549 0.96796023]
